name: RSS a Slack (Diario)

on:
  schedule:
    # Cron expression para 'todos los días hábiles de 7:00 a 17:00 hora Argentina'
    # Nota: GitHub Actions usa la hora UTC. Argentina (GMT-3) es 3 horas detrás.
    # Por lo tanto, 7:00-17:00 en Argentina es 10:00-20:00 en UTC.
    - cron: '0 10-20 * * 1-5'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Ejecutar script
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          python main.py
