name: RSS a Slack (Diario)

on:
  schedule:
    # Se ejecuta todos los días hábiles de 7:00 a 17:00 hora Argentina
    - cron: '0 10-20 * * 1-5'
  workflow_dispatch:
    # Esto permite ejecutar el workflow manualmente desde GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Ejecutar script
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          python main.py
