name: RSS a Slack (Diario)

on:
  schedule:
    # Se ejecuta a los 25 minutos de cada hora para fines de prueba
    - cron: '25 * * * *'
  workflow_dispatch:
    # Esto permite la ejecución manual

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Ejecutar script
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          python main.py
